import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={`bg-gradient-to-br from-purple-900 via-purple-800 to-indigo-900 text-white overflow-x-hidden`}
        style={{ height: "auto", minHeight: "100%" }}
        cz-shortcut-listen="true"
      >
        
        {children}
      </body>
    </html>
  );
}
